name: appbook
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_linkify: ^6.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.16.1
  syncfusion_flutter_pdfviewer: ^25.1.39

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/github.png
  - assets/images/photoId.jpg
  - 'assets/images/user_profile.png'
  - 'assets/images/reunionFlag.png'
  - assets/docs/cvThomasOrtaDevWebApp.pdf
